### ISSUE TITLE
Make ::backdrop { display: block } not important

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#25]
Context: https://codereview.chromium.org/1372413004/

CC @upsuper @rocallahan @esprehn

**Comment by esprehn** [comment]
At most I think it needs to be coerced to a block display type like floats and positioning per the mapping here:

https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/css/resolver/StyleAdjuster.cpp&q=StyleAdjuster.cpp&sq=package:chromium&l=58

actually looking at the code (per the spec apparently) static and relative in the top layer compute to absolute, so ::backdrop is always positioned somehow, so it's already coerced to a block display type always.

**Comment by annevk** [comment]
So we could just remove this line altogether? Sounds reasonable.

**Comment by upsuper** [comment]
Authors can always use `visibility: hidden` or `opacity: 0` for hiding it, can't they?

> so ::backdrop is always positioned somehow, so it's already coerced to a block display type always.

This makes sense to me. I was mainly concerned about the layout-internal values e.g. `table-*` and `ruby-*`, but it seems all of them will be coerced to `block` because of being positioned.

After staring at our code, I have one more concern which is `display: contents`. According to the CSS Display spec, this value does not generate any box [1], and thus it is not affected by value of `position`. I guess it is fine to just treat it as `none` in this case.

There are several other block display values I don't really want to handle, but I guess they are fine.

> So we could just remove this line altogether? Sounds reasonable.

If we decide not to force it, I think it's fine to just remove that line altogether.


[1] https://drafts.csswg.org/css-display-3/#box-generation
