### ISSUE TITLE
Allow fullscreen to be triggered by an orientation change event

### ISSUE THREAD

**Issue by mounirlamouri** [whatwg/fullscreen#34]
On mobile devices, a common user experience is to have videos play inline when the device is in portrait mode and fullscreen when the user changes the orientation to landscape. Unfortunately, this is not possible on the Web because of the user gesture requirement to go fullscreen.

Changing the user gesture definition to include orientation change is unlikely a good idea because it wouldn't be appropriate for more dangerous features than fullscreen (eg. gUM). However, for fullscreen, and maybe other features, orientation change can be a good signal.

Chrome is willing to ship this ASAP. Anne, would Mozilla be interested to implement this change?

/CC @foolip

**Comment by annevk** [comment]
Paging @upsuper.

**Comment by upsuper** [comment]
It sounds fine to me, but I'd like to hear from our security team first. But I guess it would be fine as far as it is mobile-only. Filed [bug 1257029](https://bugzilla.mozilla.org/show_bug.cgi?id=1257029) on our bugzilla.

**Comment by foolip** [comment]
Would it be possible to get the rotation+fullscreen transition with no bad frames with this solution? I suspect not. What should be possible in principle even if not in implementation from day one, is to have one frame in portrait non-fullscreen, and the next in landscape fullscreen.

I think the only way this could work is to connect, ahead of time, certain rotations with the fullscreening of certain elements.

```WebIDL
enum FullscreenOrientationType {
    "none",
    "landscape",
    "portrait",
};

partial interface ScreenOrientation {
  attribute FullscreenOrientationType fullscreenOrientation;
  attribute Element? fullscreenElement;
};
```

Or something. Is there any other way around it?

**Comment by upsuper** [comment]
If the related event is dispatched before the first frame is painted in landscape, I guess that is possible to have no bad frame in theory.

**Comment by foolip** [comment]
The timing of the event is in https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes but isn't what it would need to be right now.

For consistency with the fullscreen API, I think it would make the most sense if the orientation change event (ignoring fullscreen now) is dispatched in an animation frame task for the first frame after the viewport size change.

But it's an interesting idea to fire it earlier. It would have to be at the last frame before the rotation is observable, and there would have to be a guarantee that requesting fullscreen at that time would either fail or succeed before the next frame is drawn. This sounds a bit tricky, I'm guessing that right now Blink is simply informed that it has been rotated, and it block the rotation on a response from the main thread could be hard.

Does the declarative approach look terrible, or might it not be powerful enough?

**Comment by mounirlamouri** [comment]
@upsuper I am not sure why this has to be mobile-only. FWIW, non-mobile devices usually don't have orientation changes. For the sack of consistency, I would prefer this to be for all platforms.

@foolip I'm not sure the declarative approach is the right approach at the moment. We might paint ourselves in a corner for something that is not yet a problem. My basic tests seem to show that there is indeed one frame between the event and fullscreen happening but it's barely visible. I don't think allowing to go fullscreen on orientation change is a major platform change and I would say that it will open new use cases that we might want to polish later.

**Comment by foolip** [comment]
It sounds like a bad frame is confirmed by your testing, and that problem will neither grow nor shrink by waiting. If the orientation change event is eventually spec'd and implemented similarly to fullscreen, i.e. it is fired as an animation frame task at the first frame after the transition, then no amount of later polish could close this gap. In other words, to fix the problem later would by necessity duplicate the "fullscreen on rotate" functionality in some way.

So, what would it take to guarantee no bad frames, at a minimum? An alternative to teaching the orientation API about fullscreen could be to teach the fullscreen API about orientation:
```JavaScript
element.requestFullscreen({ requireOrientation: 'landscape' });
```
If we're already in landscape *and* there's a user gesture it could go fullscreen immediately, and otherwise it'll wait for a rotation. Might benefit from cancelable promises to cancel the request before it happens, but a v1 without that might be OK too.

Maybe. Other ideas?

**Comment by foolip** [comment]
To be clear, I wouldn't be particularly concerned if an initial implementation has a bad frame or even ten, as long as it's fixable without changing the spec/model.

**Comment by mounirlamouri** [comment]
Actually, if you want to go into details, there are two issues:
* rotate while going fullscreen
* go fullscreen while rotating

I guess both would have their own set of frame issues.

However, I'm not sure why we should consider fullscreen an exception. Any kind of layout change on rotation will be subject to bad frame: what if there are some media queries that would apply? Or if the page remove/add contents? Should this be solved at a different level and make the orientation change able to deal with that kind of issues?

**Comment by foolip** [comment]
The animation frame callback timing is such that any changes made to style or DOM should apply to the frame that follows, which is be the first frame after the transition, whether it is fullscreen or orientation. This has at least been my assumption since the fullscreen spec began using animation frame tasks to solve the bad frame problem, so I sure hope I'm right :)

I agree that "rotate while going fullscreen" is a very interesting case, and it seems like one could want only one of these behaviors and that they could be treated separately, but used together. Very verbosely, the semantics might be `requestFullscreen({ delayFullscreenUntilRotationIs: 'landscape', ifGoingFullscreenDueToUseGestureRotateTo: 'landscape' })`. Seems OK to deal with "go fullscreen while rotating" first, only making sure that it could be sensible extended later.

**Comment by mounirlamouri** [comment]
Reviving this: we had more discussions about the issue internally and today Chrome will not be able to implement a nice and smooth solution without bad frames even with a dedicated API. Chrome Android has issues with this that go beyond the API (try to rotate a playing fullscreen <video>). Fixing these issues isn't trivial.

I believe that there is no point in designing an API that couldn't be implemented significantly better than making the two calls. Having an incremental approach here would help: allow usage of Fullscreen + Screen Orientation APIs then build a better API. I wouldn't want us to delay offering this feature to the mobile web hoping to have the perfect API ready.

It seems that both the Firefox and Chrome security teams see no issues in allowing fullscreen requests on orientation changes. Should we go forward with the change then?

**Comment by foolip** [comment]
I think it'd be very unfortunate to have an API that nobody could implement without bad frames, but if you can get support (or lack of objections) from the relevant people working on other engines, I will happily accept the situation. (Something like https://github.com/whatwg/fullscreen/issues/34#issuecomment-197141721 seems simple enough and is possible to feature detect, but I won't be the one writing the spec or doing the work, so...)

**Comment by mounirlamouri** [comment]
I agree but I don't want the ideal solution to block having the feature available to the platform. If we wait for the perfect solution, it might take years before it happens. Allowing fullscreen to be requested on orientation change would take a quick spec change and a quick implementation change and later, if there is enough traction, it will help push for a better smoother solution.

Also, it's not introducing an API, just allowing websites to call requestFullscreen() in an orientation change event, the same way they can call requestFullscreen() and orientation.lock() one after each other (which also will create bad frames and we can't prevent websites from calling these methods).

**Comment by foolip** [comment]
Hmm, wait, no user gesture is required to call `screen.orientation.lock()`, right? And yet the resulting `change` event can be used to get past the user gesture requirement for `element.requestFullscreen()`?

Or is it possible to distinguish the reason for an orientation change?

Regarding perfection, I honestly don't think a solution that *allows* for implementations with no bad frames seems like particularly much more spec work, and feature detection seems useful to have. But at this point I think this should be decided by seeking feedback from all implementers about what they'd be willing to implement.

**Comment by upsuper** [comment]
Let me raise another question: what are other dangerous features which currently require and only require a user gesture to activate?

@mounirlamouri's example on the top of this issue is gUM, but as far as I can see, `getUserMedia` does not require a user gesture at all, not in Firefox, Chrome, or Edge. Asking for access to camera or microphone would always require an explicit approval from the user, rather than a simple user gesture. And given the requirement of an explicit approval, whether it is from a user gesture is not relevant.

Having said this, I think the right way to go for now is probably to make orientation change event a user gesture in the HTML spec, not an exception here. But the question @foolip just raised also needs consideration. It seems to me that the timing of firing `change` event in the current Screen Orientation API spec isn't clear enough. I think that timing need to be clear before it can be added as a user gesture.

 (Actually, I don't think browsers follow the spec for what is considered as a user gesture. For example, `keypress` is not listed there, but I believe all browsers consider that event as a user gesture for opening popup and entering fullscreen, and holding back that would certainly break the web. At least Youtube uses keypress for fullscreen.)

**Comment by mounirlamouri** [comment]
@foolip `screen.orientation.lock()` requires a user gesture so you can't work around the user gesture restriction of `requestFullscreen` with the Screen Orientaiton API.

@upsuper I don't think we should add the orientation change event as a user gesture in the HTML specification because things requiring user gestures are very different and I don't think users would like for popups to open when they rotate their screen. I would prefer an incremental change where only `requestFullscreen` accepts an orientation change as a valid input.

I think it's fair to strengthen the timing of the Screen Orientation API's `change` event if it's not clear enough. What do you guys think should be clarified?

**Comment by foolip** [comment]
I couldn't see a user gesture check in Blink's `ScreenOrientation::lock` so I assumed there wasn't one, is it handled elsewhere? The [spec](https://w3c.github.io/screen-orientation/#dom-screenorientation-lock) doesn't explicitly really require it.

(I tried to write a simple test for it, but failed to get it working in Chrome for Android.)

For the `change` event, I think it's https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes that needs to change. It needs to be something like https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen which says "As part of the next animation frame task, run these substeps" but also "Animation frame task is not really defined yet" :)

**Comment by mounirlamouri** [comment]
It's been a while and indeed my memory failed me: there is no user gesture required. I now remember the reason: we wanted games to be able to have dynamic orientation changes and we concluded that the benefits from abusing this was inexistent so adding too many restrictions wasn't worth it. I can ping back the security team and see if they would consider this a problem. We can always restrict user gesture as an action when it is actually user initiated.

Regarding the animation frame task, there is an open bug to do this change in the Screen Orientation API but given that it was never really defined, I have not seen the benefit of doing so. I can do that if it can unblock us here but in practice, will it change something?

**Comment by upsuper** [comment]
> For the change event, I think it's https://w3c.github.io/screen-orientation/#handling-screen-orientation-changes that needs to change. It needs to be something like https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen which says "As part of the next animation frame task, run these substeps" but also "Animation frame task is not really defined yet" :)

Actually not only this... I filed w3c/screen-orientation#89 for that.

**Comment by upsuper** [comment]
It doesn't seem to me require user gesture for locking orientation sounds like the right restriction.

I guess we could either have a flag indicating whether a change event is from a device orientation change or orientation lock, or have a separate event which always fires when the device tries to change the orientation of the view (but may be prevented because of orientation lock).

**Comment by upsuper** [comment]
For the bad frame issue, I'm not particularly concerned, and I'm not a fan of adding declarative way for entering fullscreen. I don't think that's very useful.

I guess that issue could probably be solved in a more general way in the HTML spec, for example, say user agent may skip updating the rendering in certain conditions.

**Comment by foolip** [comment]
@mounirlamouri 
> Regarding the animation frame task, there is an open bug to do this change in the Screen Orientation API but given that it was never really defined, I have not seen the benefit of doing so. I can do that if it can unblock us here but in practice, will it change something?

It wouldn't fix any problem, it would just make the timing of the bad frame clear.

@upsuper 
> I guess that issue could probably be solved in a more general way in the HTML spec, for example, say user agent may skip updating the rendering in certain conditions.

Something like if there's a pending fullscreen request after all of the animation frame callbacks and animation frame tasks (that fire events) have run then don't draw any new frames for a while?

**Comment by foolip** [comment]
Figuring out the user gesture requirement seems more important, though. I assume that if left alone, one could change the screen orientation and go to fullscreen without a user gesture, and then either change the orientation back (while staying) in fullscreen or just drawing fake system UI rotated to match the original orientation.

**Comment by mounirlamouri** [comment]
I've just committed some changes to the screen orientation api spec. It should address @upsuper comments. Also, @foolip, it's now using the animation frame task.

@foolip, wouldn't your lastest concern be resolved if we do not allow to go fullscreen when the orientation change is a result of `orientation.lock()`?

**Comment by foolip** [comment]
Yes, there is a subset of `orientationchange` events which are the result of the user either rotating the device or (perhaps) `orientation.lock()` being called with a user gesture, so only allowing those to trigger fullscreen would address that concern.

**Comment by foolip** [comment]
Still curious if anyone thinks that it will be *possible* to avoid the bad frame with incremental changes to this model in the future, even if that's not an implementation priority now.

**Comment by mounirlamouri** [comment]
/CC @jernoble FYI and if you have any comments

@foolip not sure what you meant.

**Comment by foolip** [comment]
My view is that an API of a completely different shape would be needed to avoid the bad frame in the future (if it becomes a priority for some implementer) and I was basically asking if anybody saw it differently, if there is an incremental change that could fix it. (Don't wish to restart the discussion here, just noticed that I hadn't replied to the request for clarification.)

**Comment by StarNeit** [comment]
hello guys.
I want my website to trigger full screen mode after a screen orientation change.
But, it says that it requires user gesture.

can you please let me know how to trigger full screen when a device orientation change?
thank you.

**Comment by upsuper** [comment]
Invoke `element.requestFullscreen()` in handler of [`change` event of `screen.orientation`](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/onchange) should do that. Note that not all browsers support this currently. (Actually probably only Chrome supports it at the moment.)
