### ISSUE TITLE
Should we apply !important to "object-fit: contain"?

### ISSUE THREAD

**Issue by upsuper** [whatwg/fullscreen#44]
I wonder do we have a good reason to apply `!important` to `object-fit: contain` in the UA style sheet?

I think there are reasonable cases that authors may want to make the content of element stretch to fill the whole screen.

Probably we can remove `!important` from `object-fit: contain`?

**Comment by foolip** [comment]
Looks like it originated in 2b8bb8d5cb2e2406d194cd74f4f3e44a077ab142 and then `!important` was added in 134cdeb6d6d3f7c3bdb3c9df754185c24a59353f because of https://www.w3.org/Bugs/Public/show_bug.cgi?id=26480

I wonder if we need to fiddle with `object-fit` at all? Blink doesn't have it currently, but I was just about to add it as part of the top layer rewrite. Should I try to just not add it and have it removed from the spec if that works out?

**Comment by upsuper** [comment]
So it seems there was actually no direct reason `object-fit` should have `!important`, so it shouldn't have that I believe.

**Comment by foolip** [comment]
What I'm saying is that maybe the spec doesn't need to mention `object-fit` at all? I can't quite figure out the original meaning of 2b8bb8d5cb2e2406d194cd74f4f3e44a077ab142, so it's hard to say. @annevk?

**Comment by upsuper** [comment]
I do think `object-fit: contain` itself makes sense, because when we put something in fullscreen, people in general should expect the aspect ratio of the content is not changed.

**Comment by foolip** [comment]
I didn't realize the intent before, but it looks like this bit of CSS in the existing Blink code (before the top layer rewrite) is to make this work for images, at least images that have a width:height ratio smaller than the screen:
```CSS
img:-webkit-full-screen {
    width: auto;
    height: 100%;
    max-width: 100%;
}
```

`object-fit: contain` will achieve the same thing but also for wide images, so just dropping `!important` sounds OK to me.

**Comment by annevk** [comment]
It was also there to make sure videos would not resize in a weird way. I'll remove `!important` though.
