### ISSUE TITLE
Drop the iframe ancestor check?

### ISSUE THREAD

**Issue by foolip** [whatwg/fullscreen#45]
This was last changed in 0257af72893471c98f2c006777c8aa59ab668818 and seems to have originated in e6fa2d688e713d371eeaf80c6266179230d06f69.

After 0b7c994bfcedb291cb9ab7398b26cb4a575470d1 and 766dc872bcf26c012549f7bdfde21c46bebba40c there are no other hierarchy restrictions, and there's probably no reason to keep the iframe ancestor check. By itself, it doesn't seem to provide any interesting guarantees.

Motivation: Removing this *may* make it easier to propagate the result of the fullscreen element ready check to other processes, currently being discussed in https://bugs.chromium.org/p/chromium/issues/detail?id=402376#c13

@upsuper

**Comment by upsuper** [comment]
IIUC, that is about something in the same document between `<iframe>` and `</iframe>`?

Does `<iframe>` really have any descendant element? It seems to me browsers agree on the behavior that any content between `<iframe>` and `</iframe>` are just parsed as raw text, and would not construct any element. And this is also what the HTML Standard says [1].

So if that is what we are discussing here, I think it makes sense to just remove this check, because now it no longer makes any sense given the HTML parsing algorithm. And based on this, I don't quite believe having this check or not could make anything easier or harder.


[1] Search `A start tag whose tag name is "iframe"` in [this page](https://html.spec.whatwg.org/multipage/syntax.html).

**Comment by foolip** [comment]
You can always do `iframe.appendChild(element); element.requestFullscreen()`. Crazy, but I think avoiding a tab-wide set of fullscreen elements that don't form a simple ancestor-descendant chain was the original reason for this.

**Comment by upsuper** [comment]
Oh, smart, okay, that makes sense.

So Gecko doesn't have such check, and it seems Safari doesn't either. Not sure Edge's status (I'm not on Windows currently), but I guess it does make sense to remove this restriction if it makes implementation easier.

(But that makes me wonder whether that could make current implementations crazy somehow... Hopefully no security issue exposed...)

**Comment by foolip** [comment]
I added the restriction in Blink in https://codereview.chromium.org/462103002 but I'd be happy to remove it again, and it's encouraging to hear that Gecko doesn't have it.

**Comment by annevk** [comment]
We should probably drop it, since the same situation can occur with `frame` or `object`.

**Comment by annevk** [comment]
(Note that without DOM manipulation, this situation can also arise through usage of XML.)

**Comment by foolip** [comment]
I agree with dropping, but how would something similar happen with `frame` or `object` when things in those containers can't go fullscreen at all?

**Comment by upsuper** [comment]
Those elements themselves can go fullscreen, and probably like `iframe`, their children are never displayed.

**Comment by foolip** [comment]
Ah, yes. I suppose the problem applies to all replaced content like `img` and `video` and form controls like `input`, `button` and `textarea`.
